<a href="https://colab.research.google.com/github/Joshan2005/Petroleum-Data-Analytics/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

In [ ]:
pip install numpy

In [ ]:
# creating 1D array
import numpy as np
a1 = np.array([1,2,3])
print(a1)

[1 2 3]


In [ ]:
# creating 2D array
import numpy as np
a2 = np.array([[1,2,3],[4,5,6]])
print('Dimensions:',a2.ndim)
print(a2)

Dimensions: 2
[[1 2 3]
 [4 5 6]]


In [ ]:
# creating 3D array
import numpy as np
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print('Dimensions:',a3.ndim)
print(a3)

Dimensions: 3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# ndarray funtions
import numpy as np
a3 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print('Shape:',a3.shape)
print('Dimensions:',a3.ndim)
print('Size:',a3.size)
print('Data type:',a3.dtype)
print('Item size:',a3.itemsize)

Shape: (4, 3)
Dimensions: 2
Size: 12
Data type: int64
Item size: 8


In [ ]:
# creating a sequence of evenly spaced values
import numpy as py
a4 = np.arange(20,40,2)
print(a4)

[20 22 24 26 28 30 32 34 36 38]


In [ ]:
# returning elemnets at indices
import numpy as np
a5=a4[np.array([1,2,3])]
print(a5)

[22 24 26]


In [ ]:
# basic slicing
import numpy as np
a6=np.arange(0,10,1)
print(a6[6])
print(a6[2:8:2])

6
[2 4 6]


Advanced Indexing

In [ ]:
# integer indeging
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print(a,'\n')
print(a[[0,1,2],[0,0,1]])

[[1 2]
 [3 4]
 [5 6]] 

[1 3 6]


In [ ]:
# boolean indexing
import numpy as np
a = np.array([20,40,60,80,100])
print(a[a>60])

[ 80 100]
